name: release

on:
  push:
    tags:
      - v*

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-go@v3
          with:
            go-version-file: go.mod
            cache: true

      # リリース
        - uses: goreleaser/goreleaser-action@v4
          with:
            args: release --rm-dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自動で生成されるシークレット
